stages:
    - build
    - deploy

publish-org:
    stage: build
    image: iquiw/alpine-emacs
    before_script:
        - apk add --no-cache --update sqlite git
    script:
        - emacs -Q --batch -l build-site.el --funcall jh/publish-org
    artifacts:
        paths:
        - public
        - org

generate-css:
    stage: build
    needs: [publish-org]
    image: node:latest
    script:
        - npm ci
        - npm run build-css:production

publish-assets:    
stage: build
    image: iquiw/alpine-emacs
    before_script:
        - apk add --no-cache --update sqlite git
    script:
        - emacs -Q --batch -l build-site.el --funcall jh/publish-assets
    artifacts:
        paths:
        - public

pages:
  <<: *build
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

test:
  <<: *build
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH

