stages:
    - build
    - deploy

publish-org:
    stage: build
    image: iquiw/alpine-emacs
    before_script:
        - apk add --no-cache --update sqlite git
    script:
        - emacs -Q --batch -l build-site.el --funcall jh/publish-org
    artifacts:
        paths:
        #- public
        - org
        - .emacs.d

generate-css:
    stage: build
    needs: [publish-org]
    image: node:latest
    script:
        - npm ci
        - npm run build-css:production

publish-assets:    
    stage: build
    image: iquiw/alpine-emacs
    needs: [publish-org, generate-css]
    before_script:
        - apk add --no-cache --update sqlite git
    script:
        - emacs -Q --batch -l build-site.el --funcall jh/publish-assets
    artifacts:
        paths:
        - static

pages:
    stage: deploy
    needs: [publish-org, publish-assets]
    image: iquiw/alpine-emacs
    script:
        - emacs -Q --batch -l build-site.el --funcall org-publish-all
    artifacts:
        paths:
            - public
